### ISSUE TITLE
[FeatureRequest] BloodHound-CE support

### ISSUE THREAD

**Issue by ag-michael** [NH-RED-TEAM/RustHound#19]
Hi NH-RED-TEAM,

I just wanted to open a feature request to support bloodhound-ce/5.0. Rusthound has been working great on Linux but automating the collection means we need to use bloodhound-ce, right now there are some missing fields/details and it does not work well in -CE.

**Comment by g0h4n** [comment]
Hi @ag-michael,

I'm currently working on it :) !

**Comment by ag-michael** [comment]
Thank you very much @g0h4n  look forward to it!

**Comment by g0h4n** [comment]
RustHound is now compatible with [BloodHound-CE](https://github.com/SpecterOps/BloodHound) can be find in [v2 branch](https://github.com/NH-RED-TEAM/RustHound/tree/v2). :rocket: 

https://github.com/NH-RED-TEAM/RustHound/commit/b445723c0330c5b3e5c237d5632625379bf48fbf

Don't hesitate to test version 2.0
This will become the main branch asap. :smiley:

**Comment by ag-michael** [comment]
Thanks very much @g0h4n this is great news! Happy holidays/new years.
