### ISSUE TITLE
Spelling mistake 

### ISSUE THREAD

**Issue by LarsVonZipper** [NH-RED-TEAM/RustHound#21]
Hi.
I think there is a spelling mistake in SRC/JSON/parser/bh_41.rs lines 406 and 589
It's causing the following:

![image002](https://github.com/NH-RED-TEAM/RustHound/assets/32393030/75a0a9d8-2fe6-4271-98cd-272e81689fd2)

The misspelt word is "samaccoutname". You have missed out the 'n' between the 'u' and the 't'. It should read, "samaccountname".
I think I'm supposed to do a "pull request" but, I'm new to this GitHub stuff and have got a clue how. Apologies

**Comment by g0h4n** [comment]
Hi @LarsVonZipper,

Thanks ! I fixed it :)
